trigger:
- main

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: azure-resource-connection
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
