trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  - group: dp100-aml-vg

steps:
- task: AzureCLI@2
  displayName: Create AML Workspace with Azure CLI
  inputs:
    azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
      az group create --name "$(RESOURCE_GROUP)" --location "$(LOCATION)"
      az configure --defaults group="$(RESOURCE_GROUP)" workspace="$(WORKSPACE_NAME)"
      az ml workspace create
